version: "3"

services:
  project:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project
    environment:
      DB_URI: "mysql+pymysql://root:pass_db@project_db/prueba"
    image: cognitive_g6/project
    ports:
      - "5000:5000"
    restart: unless-stopped

  project_db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: project_db
    environment:
      MYSQL_ROOT_PASSWORD: pass_db
    image: cognitive_g6/project_db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
